# playlist_data.py
# Curated playlist for 21-year-old preferences (rap, country, classic, pop, Guardians of the Galaxy, Adele, Bruno Mars)

playlist = [
    # Rap
    "Doja Cat - Paint The Town Red",
    "Dave & Central Cee - Sprinter",
    "Gunna - Fukumean",
    "Metro Boomin ft. Don Toliver & Future - Too Many Nights",
    "Metro Boomin ft. Travis Scott & Young Thug - Trance",
    "Nicki Minaj & Ice Spice ft. Aqua - Barbie World",
    "Central Cee - LET GO",
    "Lil Uzi Vert - Watch This (ARIZONATEARS Pluggnb Remix)",
    "Travis Scott - I KNOW ?",
    "Drake ft. J. Cole - First Person Shooter",
    "GloRilla & Cardi B - Tomorrow 2",
    "J.I.D ft. 21 Savage & Baby Tate - Surround Sound",
    "Sleepy Hallow - Die Young",
    "Drake & 21 Savage - Rich Flex",
    "Gucci Mane & Kodak Black - King Snipe",
    "Trippie Redd ft. Juice WRLD - KNIGHT CRAWLER",
    "Armani White - Billie Eilish",

    # Country
    "Luke Combs - Fast Car",
    "Morgan Wallen - Last Night",
    "Morgan Wallen - You Proof",
    "Megan Moroney - Tennessee Orange",
    "Lainey Wilson - Watermelon Moonshine",
    "Brett Young - You Didn't",
    "Jason Aldean - Try That In A Small Town",
    "Cody Johnson - Human",
    "Bailey Zimmerman - Religiously",
    "Dustin Lynch - Stars Like Confetti",
    "Thomas Rhett & Riley Green - Half Of Me",
    "Carly Pearce - What He Didn't Do",
    "Old Dominion - Memory Lane",
    "Morgan Wallen - Thought You Should Know",
    "Tyler Hubbard - Dancin' In The Country",
    "Bailey Zimmerman - Rock and A Hard Place",
    "Kane Brown & Katelyn Brown - Thank God",
    "Nate Smith - Whiskey on You",
    "Jelly Roll - Son of a Sinner",
    "Zach Bryan ft. Kacey Musgraves - I Remember Everything",

    # Classic Rock & Guardians of the Galaxy songs
    "Blue Swede - Hooked on a Feeling",
    "Redbone - Come and Get Your Love",
    "Electric Light Orchestra - Mr. Blue Sky",
    "Fleetwood Mac - The Chain",
    "David Bowie - Moonage Daydream",
    "Looking Glass - Brandy (You're a Fine Girl)",
    "Jackson 5 - I Want You Back",
    "Sweet - Fox on the Run",
    "Cheap Trick - Surrender",
    "The Spinners - The Rubberband Man",
    "Led Zeppelin - Stairway to Heaven",
    "Queen - Bohemian Rhapsody",
    "The Eagles - Hotel California",
    "Pink Floyd - Time",
    "The Beatles - A Day in the Life",
    "Aerosmith - Sweet Emotion",
    "The Beatles - Come Together",
    "Queen - Another One Bites The Dust",
    "AC/DC - Back In Black",
    "Journey - Don't Stop Believin'",
    "Heart - Barracuda",
    "Kansas - Carry On Wayward Son",
    "Scorpions - Rock You Like A Hurricane",
    "Led Zeppelin - Black Dog",
    "Nirvana - Smells Like Teen Spirit",
    "The Rolling Stones - Satisfaction",
    "The Clash - London Calling",
    "Van Halen - Runnin' With The Devil",
    "Jimi Hendrix - Voodoo Child (Slight Return)",
    "Black Sabbath - War Pigs",
    "Rush - Tom Sawyer",

    # Pop (with Adele and Bruno Mars emphasis)
    "Miley Cyrus - Flowers",
    "Taylor Swift - Cruel Summer",
    "PinkPantheress & Ice Spice - Boy's a liar Pt. 2",
    "Troye Sivan - Rush",
    "Olivia Rodrigo - Bad Idea Right?",
    "Carly Rae Jepsen - Psychedelic Switch",
    "Lana Del Rey - A&W",
    "boygenius - Not Strong Enough",
    "Dua Lipa - Houdini",
    "Kylie Minogue - Padam Padam",
    "SZA - Kill Bill",
    "Charli XCX - Speed Drive",
    "Billie Eilish - What Was I Made For?",
    "Dua Lipa - Dance the Night",
    "Mitski - My Love Mine All Mine",
    "Rema & Selena Gomez - Calm Down",
    "The Weeknd & Ariana Grande - Die for You (Remix)",
    "Taylor Swift - Anti-Hero",
    "Metro Boomin, The Weeknd & 21 Savage - Creepin'",
    "David Guetta & Bebe Rexha - I'm Good (Blue)",
    "Sam Smith & Kim Petras - Unholy",
    "Adele - Hello",
    "Adele - Rolling in the Deep",
    "Adele - Set Fire to the Rain",
    "Adele - Someone Like You",
    "Bruno Mars - 24K Magic",
    "Bruno Mars - Treasure",
    "Bruno Mars - Locked Out of Heaven",
    "Bruno Mars - That's What I Like",
    "Bruno Mars & Anderson .Paak - Leave The Door Open",
    "Ed Sheeran - Shape of You",
    "The Weeknd - Blinding Lights",
    "Harry Styles - As It Was",
    "Lady Gaga - Shallow",
    "Justin Bieber - Sorry",
    "Shawn Mendes - Treat You Better",
    "Katy Perry - Dark Horse",
    "Lorde - Royals",
    "Imagine Dragons - Believer",
    "Maroon 5 - Sugar",
    "Dua Lipa - New Rules",
]
